add components and style
TTurkevich/player pull request #1
Opened 2022-07-19 13:49 UTC by TTurkevich

Домашка 2. 
Разбить верстку на компоненты. Добавлены стили для наглядности.

2022-07-20 08:03 UTC, mrerberg commented
У тебя очень глубокая вложенность компонентов, что затрудняет ревью и может затруднить навигацию в проекте. Рекомендую сделать так:

допустим, у тебя есть обособленный большой компонентов Player (Bar). Разместим его в папке components

```
-- src
---- components
------ Player
```

У Player есть свои внутренние компоненты, которые нужны только ему. Так сделай проскую структуру папки Player

```
-- src
---- components
------ Player/
-------- index.jsx (Тут собирается весь компонент из кусочков)
-------- index.module.css 
-------- Controls/ (папка с дочерними компонентами)
-------- Bar/ (папка с дочерними компонентами)
```

2022-07-21 08:23 UTC, mrerberg commented
Footer

Данный компонент не нужен, так как он пустой, надо будет добавить контент - добавишь позже.

2022-07-21 08:24 UTC, mrerberg commented
Рекомендую в корневых папках компонента делать файл index.jsx, а не, например, Player.jsx, чтобы сократить путь импорта

```
import Player from './components/Player'
// vs
import Player from './components/Player/Player'
```

2022-07-21 08:36 UTC, mrerberg requested changes

2022-07-21 08:36 UTC, mrerberg commented on src/App.css
> +*:before,
Общие стили можно вынести в index.css файле, так как там и находятся глобальные стили

2022-07-21 08:36 UTC, mrerberg commented on src/components/Bar/Bar.jsx
> +import classes from './Bar.module.css'
Ты одновременно используешь и css модули и обычные классы className="container", выбери 1 вариант

2022-07-21 08:36 UTC, mrerberg commented on src/components/Bar/Bar.jsx
> +import classes from './Bar.module.css'
Я бы назвал данный компонент Player, мне кажется данное название более логичным. Что думаешь?

2022-07-25 19:05 UTC, TTurkevich commented on src/App.css
> +*:before,
Хорошо

2022-07-25 19:06 UTC, TTurkevich commented on src/components/Bar/Bar.jsx
> +import classes from './Bar.module.css'
Хорошо

2022-07-25 19:06 UTC, TTurkevich commented on src/components/Bar/Bar.jsx
> +import classes from './Bar.module.css'
Ок

2022-07-26 07:22 UTC, mrerberg commented
компонент Title независимый, почему он находится в MainContent c точки зрения структуры папок?

2022-07-26 07:23 UTC, mrerberg requested changes

2022-07-26 07:23 UTC, mrerberg commented on src/components/icons/Like/index.jsx
> +      <use
В целом, ты можешь не использовать xlinkHref, ты можешь сюда вставить в прямом смысле начинку самой svg. Так ты ее сможешь кастомизировать гибко

2022-07-26 07:23 UTC, mrerberg commented on src/components/icons/Shuffle/index.jsx
> +    <svg className={className} alt="shuffle">
Смотри, у тебя обертка svg повторяется, в ней лишь меняется className и alt. Можно вынести в отдельный компонент, например, Svg

2022-07-26 07:23 UTC, mrerberg commented on src/components/TrackItems/Album/index.jsx
> +const Album = ({ classNameDiv, classNameLink, title }) => {
Вопрос у меня к компоненту TrackItems. Смотри, я бы назвал данный компонент TrackItem, чтобы он был компонентом трека, и здесь бы реализовал (собрал) в index.jsx из других компонентов

2022-07-26 07:23 UTC, mrerberg commented on src/components/TrackItems/Album/index.jsx
> +const Album = ({ classNameDiv, classNameLink, title }) => {
Предлагаю

classNameDiv -> wrapperClassName
classNameLink -> linkClassName

Лучше никогда не указывать в именах классов теги (div), изменится тег, придется и класс менять

2022-07-26 07:23 UTC, mrerberg commented on src/components/Sidebar/Selections/index.jsx
>        <a className={classes.sidebar__link} href="#">
Если ты пишешь на css modules, тебе не нужен БЭМ. link, item

2022-07-26 07:23 UTC, mrerberg commented on src/components/Sidebar/Recommendations/index.jsx
> +          alt={"energie"}
Зачем фигурные скобки вокруг строки?

2022-07-26 07:23 UTC, mrerberg commented on src/components/Player/LikeDislike/index.jsx
> +      className={`${classes['track-play__like-dis']} ${classes['_btn-icon']}`}
Для комбинации классов рекомендую библиотеку classnames

2022-07-26 07:23 UTC, mrerberg commented on src/components/MainContent/Content/Playlist/index.jsx
>  import classes from './Playlist.module.css'
компонент playlist независимый, почему он находится в MainContent  c точки зрения структуры папок?

2022-07-26 07:23 UTC, mrerberg commented on src/components/MainContent/Content/Track/index.jsx
> +const Track = (props) => {
Я писал, куда лучше разместить Track

2022-07-26 07:23 UTC, mrerberg commented on src/components/MainContent/index.jsx
> +import classes from './MainContent.module.css'
Можно просто index.module.css, так проще будет

2022-07-28 18:31 UTC, TTurkevich commented on src/components/icons/Like/index.jsx
> +      <use
Сделала отдельный глобальный компонент

2022-07-28 18:31 UTC, TTurkevich commented on src/components/icons/Shuffle/index.jsx
> +    <svg className={className} alt="shuffle">
Сделала

2022-07-28 18:33 UTC, TTurkevich commented on src/components/TrackItems/Album/index.jsx
> +const Album = ({ classNameDiv, classNameLink, title }) => {
Сделала, надеюсь, правильно поняла

2022-07-28 18:35 UTC, TTurkevich commented on src/components/TrackItems/Album/index.jsx
> +const Album = ({ classNameDiv, classNameLink, title }) => {
Хорошо, как раз думала об этом

2022-07-28 18:41 UTC, TTurkevich commented on src/components/Sidebar/Selections/index.jsx
>        <a className={classes.sidebar__link} href="#">
Имеешь ввиду, что надо заменить sidebar__item на просто item? Но тогда придется выданную нам верстку менять, я именно поэтому классы и оставила такими

2022-07-28 18:42 UTC, TTurkevich commented on src/components/Sidebar/Recommendations/index.jsx
> +          alt={"energie"}
на автомате :/

2022-07-28 18:43 UTC, TTurkevich commented on src/components/Player/LikeDislike/index.jsx
> +      className={`${classes['track-play__like-dis']} ${classes['_btn-icon']}`}
Установила, применила, спасибо

2022-07-28 18:45 UTC, TTurkevich commented on src/components/MainContent/Content/Playlist/index.jsx
>  import classes from './Playlist.module.css'
Я уже совсем запуталась, если честно, на что опираться при создании структуры...Отталкивалась от верстки.

2022-07-28 18:46 UTC, TTurkevich commented on src/components/MainContent/Content/Track/index.jsx
> +const Track = (props) => {
Изменила

2022-07-28 18:46 UTC, TTurkevich commented on src/components/MainContent/index.jsx
> +import classes from './MainContent.module.css'
Изменила

2022-07-29 08:14 UTC, mrerberg commented
fonts следует поместить в папку public

2022-07-29 08:16 UTC, mrerberg commented on src/components/Sidebar/Selections/index.jsx
>        <a className={classes.sidebar__link} href="#">
В верстке всего лишь нужно изменить класс, ты имеешь на это право. Соблюдать БЕМ с css modules бессмысленно.

2022-07-29 08:25 UTC, mrerberg requested changes

2022-07-29 08:25 UTC, mrerberg commented on src/components/GlobalSvg/index.jsx
> +const GlobalSvgSelector = ({ id, iconClassName }) => {
Так никто не делает. Что будет, если у тебя будет 100 иконок? Сделай просто из каждой иконки компонент

2022-07-29 08:25 UTC, mrerberg commented on src/components/MainContent/Title/index.jsx
> +/* <svg className={classes['playlist-title__svg']} alt="time">
Мертвый код

2022-07-29 08:25 UTC, mrerberg commented on src/components/MainContent/Title/index.jsx
> +const Title = () => {
Это компонент не Title, а это шапка таблицы с именами колонок

2022-07-29 08:25 UTC, mrerberg commented on src/components/MainContent/Title/index.jsx
> +        ИСПОЛНИТЕЛИ
Не надо капсом писать в разметке, застилизуй лучше через css

2022-07-29 08:25 UTC, mrerberg commented on src/components/MainContent/index.jsx
> +      <h2 className={classes.centerblock__h2}>Треки</h2>
Данный заголовок можно вынести в отдельный компонент, по дизайну он будет встречать несколько раз. И да, это h1, так как это единственный заголовок на странице

2022-07-29 19:34 UTC, TTurkevich commented on src/components/Sidebar/Selections/index.jsx
>        <a className={classes.sidebar__link} href="#">
Да, я читала об этом, но меня останавливала выданная верстка. Сделаю

2022-07-29 19:36 UTC, TTurkevich commented on src/components/GlobalSvg/index.jsx
> +const GlobalSvgSelector = ({ id, iconClassName }) => {
да, верно

2022-07-29 19:36 UTC, TTurkevich commented on src/components/MainContent/Title/index.jsx
> +/* <svg className={classes['playlist-title__svg']} alt="time">
удалила

2022-07-29 19:37 UTC, TTurkevich commented on src/components/MainContent/Title/index.jsx
> +const Title = () => {
прям ведь так и хотела же сделать

2022-07-29 19:38 UTC, TTurkevich commented on src/components/MainContent/Title/index.jsx
> +        ИСПОЛНИТЕЛИ
Скопировала из верстки просто, в стилях все ок. Изменила

2022-07-29 19:38 UTC, TTurkevich commented on src/components/MainContent/index.jsx
> +      <h2 className={classes.centerblock__h2}>Треки</h2>
Хорошо

2022-07-30 09:11 UTC, mrerberg requested changes

2022-07-30 09:11 UTC, mrerberg commented on src/components/Filter/index.jsx
> +        className={cn(classes.button, classes['button-author'], classes['_btn-text'])}
Если ты используешь css modules, именуй классы с camelCase

buttonAuthor

btnText

Нижнее подчеркивание из БЕМ, оно не нужно

2022-07-30 09:11 UTC, mrerberg commented on src/components/Filter/index.module.css
> +.button-author {
Зачем нужны пустые классы?

2022-07-30 09:11 UTC, mrerberg commented on src/components/Logo/index.jsx
>          src={process.env.PUBLIC_URL + '/img/logo.png'}
Укажи просто '/img/logo.png', сработает

2022-07-30 09:11 UTC, mrerberg commented on src/components/MainContent/TrackTableHats/index.jsx
> +      <div className={cn(classes.col, classes.col03)}>
Зачем тебе классы  col01-col04? :nth-of-type не поможет?

2022-07-30 09:11 UTC, mrerberg commented on src/components/Player/Buttons/index.jsx
> +          <icon.name iconClassName={classes[`${icon.iconClassName}`]} />
Если это компонент  (icon.name), то надо писать с большой буквы. Я бы переименовал ключ в объекте name на Component

И тогда

<Icon.Component>

2022-07-30 09:11 UTC, mrerberg commented on src/components/Player/LikeDislike/index.jsx
> +    <div className={classes['track-play__like-dis']}>
Давай облагородим класс, БЕМ тут не нужен

2022-07-30 09:11 UTC, mrerberg commented on src/components/Track/index.jsx
>  const Track = (props) => {
Я бы избавился от данного компонента, а TrackItem назвал бы Track. Проще так

2022-07-30 09:11 UTC, mrerberg commented on src/components/TitleTracks/index.jsx
> +const TitleTracks = () => {
Данный компонент - заголовок для всех страниц. Посмотри по макетам и убедишься. Просто Title или Heading

2022-07-30 09:11 UTC, mrerberg commented on src/components/Svg/Glass/index.jsx
> +const Glass = ({ iconClassName }) => {
Это переводится как стакан

2022-07-30 09:11 UTC, mrerberg commented on src/components/Svg/Glass/index.jsx
> +const Glass = ({ iconClassName }) => {
Проп проще назвать className, он по дефолту идет на корневой элемент. Если ты прокидываешь несколько классов, вот тогда нужны префиксы, где ты их используешь

2022-07-30 09:11 UTC, mrerberg commented on src/components/Svg/Glass/index.jsx
> +const Glass = ({ iconClassName }) => {
footerClassName, pathClassName

2022-07-30 09:11 UTC, mrerberg commented on src/components/Svg/Glass/index.jsx
> +    <svg
Рекомендую папку svg переименовать в icons, она же по сути такой и является

2022-07-30 22:38 UTC, TTurkevich commented on src/components/Filter/index.jsx
> +        className={cn(classes.button, classes['button-author'], classes['_btn-text'])}
Хорошо, сделала

2022-07-30 22:40 UTC, TTurkevich commented on src/components/Filter/index.module.css
> +.button-author {
Прям ничего нового не скажу: перенесла из выданной верстки как было. Думала, что может там дальше в них появится какой-то смысл

2022-07-30 22:41 UTC, TTurkevich commented on src/components/Logo/index.jsx
>          src={process.env.PUBLIC_URL + '/img/logo.png'}
шикарно, спасибо!

2022-07-30 22:44 UTC, TTurkevich commented on src/components/MainContent/TrackTableHats/index.jsx
> +      <div className={cn(classes.col, classes.col03)}>
ну как бы мне не зачем, но они там были )) переделала

2022-07-30 22:45 UTC, TTurkevich commented on src/components/Player/Buttons/index.jsx
> +          <icon.name iconClassName={classes[`${icon.iconClassName}`]} />
хорошо

2022-07-30 22:45 UTC, TTurkevich commented on src/components/Track/index.jsx
>  const Track = (props) => {
избавилась, мне он тоже не нравился

2022-07-30 22:45 UTC, TTurkevich commented on src/components/TitleTracks/index.jsx
> +const TitleTracks = () => {
Хорошо

2022-07-30 22:47 UTC, TTurkevich commented on src/components/Svg/Glass/index.jsx
> +const Glass = ({ iconClassName }) => {
английский покинул меня :/

2022-07-30 22:47 UTC, TTurkevich commented on src/components/Svg/Glass/index.jsx
> +const Glass = ({ iconClassName }) => {
Хорошо

2022-07-30 22:47 UTC, TTurkevich commented on src/components/Svg/Glass/index.jsx
> +    <svg
Сделано

2022-07-31 13:01 UTC, mrerberg requested changes

2022-07-31 13:01 UTC, mrerberg commented on src/components/Filter/index.module.css
> +._btnText:hover {
Нижнее подчеркивание - БЕМ. Оно не нужно

2022-07-31 13:01 UTC, mrerberg commented on src/components/Logo/index.jsx
> +      <img className={classes.image} src={'/img/logo.png'} alt="logo"></img>
src

Если у тебя строковый атрибут, скобки вокруг него не нужны

И да

<img className={classes.image} src={'/img/logo.png'} alt="logo" />

2022-07-31 13:01 UTC, mrerberg commented on src/components/Player/Buttons/index.jsx
> +          <Icon.Component className={classes[`${Icon.iconClassName}`]} />
classes[Icon.iconClassName]

2022-07-31 13:01 UTC, mrerberg commented on src/components/Sidebar/Recommendations/index.jsx
> +        <Selections image={'img/playlist01.png'} alt="day's playlist" />
Фигурные скобки не обязательны вокруг image prop

2022-07-31 13:01 UTC, mrerberg commented on src/components/Track/index.jsx
> +          wrapperClassName={classes.title}
А зачем так много передается props в Title? Не достаточно застилизовать все элементы внутри Title?

2022-07-31 13:01 UTC, mrerberg commented on src/components/Track/index.jsx
> +          wrapperClassName={classes.title}
Очень много классов прокидывается

2022-07-31 18:26 UTC, TTurkevich commented on src/components/Filter/index.module.css
> +._btnText:hover {
сто раз проверила и все же пропустила

2022-07-31 18:27 UTC, TTurkevich commented on src/components/Logo/index.jsx
> +      <img className={classes.image} src={'/img/logo.png'} alt="logo"></img>
Ок

2022-07-31 18:27 UTC, TTurkevich commented on src/components/Player/Buttons/index.jsx
> +          <Icon.Component className={classes[`${Icon.iconClassName}`]} />
Исправила

2022-07-31 18:27 UTC, TTurkevich commented on src/components/Sidebar/Recommendations/index.jsx
> +        <Selections image={'img/playlist01.png'} alt="day's playlist" />
Ок

2022-07-31 18:28 UTC, TTurkevich commented on src/components/Track/index.jsx
> +          wrapperClassName={classes.title}
да, согласна, ужасно, переделала

2022-08-02 09:15 UTC, mrerberg approved these changes

2022-08-02 09:15 UTC, mrerberg commented on src/components/Track/Title/index.jsx
> +          <span className={classes.titleSpan}>{clarification}</span>
Не указывай в названии класса тег, изменится тег - придется менять и класс

2022-08-02 13:40 UTC, TTurkevich commented on src/components/Track/Title/index.jsx
> +          <span className={classes.titleSpan}>{clarification}</span>
Хорошо

2022-08-02 13:53 UTC, merged