added modal window, skeleton, active classes
TTurkevich/player pull request #2
Opened 2022-08-09 18:48 UTC by TTurkevich

2022-08-09 19:59 UTC, yadimko requested changes
насыпал немного комментов

2022-08-09 19:59 UTC, yadimko commented on src/components/Filter/index.jsx
> +import { useState } from 'react'
поправь немного импорты - будем привыкать к коммерческим требованиям)
порядок импортов: third-party libraries, алиасы, относительные (пустая строка в качестве разделителя между группами)

2022-08-09 19:59 UTC, yadimko commented on src/components/Filter/index.jsx
> +          onChange={handleClick}
почитай здесь про useCallback. сейчас ты передаешь каждый раз новый экземпляр функции

2022-08-09 19:59 UTC, yadimko commented on src/components/FilterButton/index.jsx
> +const FilterButton = (props) => {
вместо пропсов используй деструктуризацию
const FilterButton = (props) => { было
const FilterButton = ({ onChange, ...... }) => { так лучше

2022-08-09 19:59 UTC, yadimko commented on src/components/Modal/index.jsx
> +        onClick={(e) => e.stopPropagation()}
это зачем так?

2022-08-09 19:59 UTC, yadimko commented on src/components/Navigation/Burger/index.jsx
> +const Burger = ({active, setActive}) => {
вот тут хорошо)

2022-08-09 19:59 UTC, yadimko commented on src/components/Navigation/Menu/index.jsx
> +      <ul className={classes.list} onClick={event => event.stopPropagation()}>
не понял зачем?

2022-08-09 19:59 UTC, yadimko commented on src/components/Navigation/index.jsx
> +import { useState } from 'react'
поправить импорты

2022-08-09 19:59 UTC, yadimko commented on src/components/Player/Controls/index.jsx
> +import SkeletonTrackPlay from '../../Skeleton/SkeletonTrackPlay'
импорты

2022-08-09 19:59 UTC, yadimko commented on src/components/Player/TrackPlay/index.jsx
> +            <div className={classes.image}>
почему отказалась от cn()?

2022-08-09 19:59 UTC, yadimko commented on src/components/Playlist/index.jsx
> +import trackData from '../server/trackData'
Импорты

2022-08-09 19:59 UTC, yadimko commented on src/components/Playlist/index.jsx
> +          return <Track key={index} track={track} />
если манипуляций с листом нет , то key = index норм. в обратном надо поменять

2022-08-09 19:59 UTC, yadimko commented on src/components/Sidebar/Recommendations/index.jsx
> +import selectionsData from '../../utils/selectionsData'
импорты)

2022-08-09 19:59 UTC, yadimko commented on src/components/Sidebar/Recommendations/index.jsx
> +          return <Selections key={index} selection={selection} />
тот же момент с key

2022-08-10 13:24 UTC, TTurkevich commented on src/components/Filter/index.jsx
> +import { useState } from 'react'
Хорошо, спасибо

2022-08-10 13:24 UTC, TTurkevich commented on src/components/Filter/index.jsx
> +          onChange={handleClick}
прочитала, применила, спасибо

2022-08-10 13:25 UTC, TTurkevich commented on src/components/FilterButton/index.jsx
> +const FilterButton = (props) => {
забыла исправить, теперь исправила

2022-08-10 13:26 UTC, TTurkevich commented on src/components/Modal/index.jsx
> +        onClick={(e) => e.stopPropagation()}
тоже забыла убрать, сначала по-другому написала модальное окно, исправила

2022-08-10 13:26 UTC, TTurkevich commented on src/components/Navigation/Burger/index.jsx
> +const Burger = ({active, setActive}) => {
:)

2022-08-10 13:27 UTC, TTurkevich commented on src/components/Player/TrackPlay/index.jsx
> +            <div className={classes.image}>
там два разных линка с разными стилями, поэтому просто идентифицировала какой куда

2022-08-10 13:27 UTC, TTurkevich commented on src/components/Playlist/index.jsx
> +import trackData from '../server/trackData'
ок

2022-08-10 13:29 UTC, TTurkevich commented on src/components/Playlist/index.jsx
> +          return <Track key={index} track={track} />
хорошо, я учту это далее, когда будет понятен бэкенд

2022-08-10 13:29 UTC, TTurkevich commented on src/components/Sidebar/Recommendations/index.jsx
> +import selectionsData from '../../utils/selectionsData'
ок

2022-08-10 13:29 UTC, TTurkevich commented on src/components/Sidebar/Recommendations/index.jsx
> +          return <Selections key={index} selection={selection} />
ок

2022-08-10 13:35 UTC, merged