correcting
TTurkevich/player pull request #3
Opened 2022-08-11 18:35 UTC by TTurkevich

Удалены лишние файлы react

2022-08-13 13:00 UTC, mrerberg requested changes

2022-08-13 13:00 UTC, mrerberg commented on src/components/MainContent/index.jsx
> +      <Search searchBlock={classes.searchBlock} />
А тут зачем пропс так называется? Можно же просто

className={classes.searchBlock}

2022-08-13 13:00 UTC, mrerberg commented on src/components/Heading/index.jsx
> +const Heading = ({heading}) => {
className

2022-08-13 16:31 UTC, TTurkevich commented on src/components/MainContent/index.jsx
> +      <Search searchBlock={classes.searchBlock} />
думала, чтобы путаницы не было, если в компоненте много пропсов

2022-08-13 16:31 UTC, TTurkevich commented on src/components/Heading/index.jsx
> +const Heading = ({heading}) => {
ок

2022-08-14 10:08 UTC, mrerberg commented on src/components/MainContent/index.jsx
> +      <Search searchBlock={classes.searchBlock} />
Если тебе надо прокидывать несколько классов, то другой вопрос. Но тогда надо добавлять еще приписку className: searchBlockClassName, а то не понятно, что за проп. Тебе достаточно назвать просто className

2022-08-14 10:13 UTC, merged