Improved player. Implemented the logic of play/stop buttons. Implemeted track bar status.
TTurkevich/player pull request #5
Opened 2022-09-02 17:00 UTC by TTurkevich

2022-09-04 10:10 UTC, mrerberg requested changes

2022-09-04 10:10 UTC, mrerberg commented on src/components/Player/Buttons/index.jsx
> +    playingBtn
Что это за конструкция?

2022-09-04 10:10 UTC, mrerberg commented on src/components/Player/TrackPlay/index.jsx
> +const TrackPlay = ({ track, reference }) => {
reference

Все же принято в среде разработчиков именовать как ref. Если нужно уточнить на что это ссылка, то можно так

buttonRef, playButtonRef, playerRef и тд

2022-09-04 10:10 UTC, mrerberg commented on src/components/Player/index.jsx
> +    if (audioRef && audioRef.current) {
audioRef && audioRef.current -> audioRef?.current

2022-09-04 10:10 UTC, mrerberg commented on src/components/Player/index.jsx
> +function useInterval(callback, delay) {
А зачем в целом тебе этот хук?

2022-09-04 10:10 UTC, mrerberg commented on src/components/Player/index.jsx
> +function useInterval(callback, delay) {
Вынеси его в какую-нибудь отдельную общую папку для хуков

2022-09-04 10:10 UTC, mrerberg commented on src/components/Player/index.jsx
> +function useInterval(callback, delay) {
Для переиспользуемости

2022-09-04 12:22 UTC, TTurkevich commented on src/components/Player/index.jsx
> +    if (audioRef && audioRef.current) {
ok

2022-09-04 12:24 UTC, TTurkevich commented on src/components/Player/TrackPlay/index.jsx
> +const TrackPlay = ({ track, reference }) => {
Если далее писать ref={ref}, то не работает, поэтому так развернула. Поняла, спасибо

2022-09-08 07:01 UTC, mrerberg requested changes

2022-09-08 07:01 UTC, mrerberg commented on src/components/Player/Buttons/index.jsx
> +        <div
На div лучше не вешать обработчики, для этого есть интерактивные элементы (button)

2022-09-08 07:01 UTC, mrerberg commented on src/components/Player/Buttons/index.jsx
> +          activeRepeat
Чтобы не бахать подобным образом тернарники, с помощью cn можно задавать условные классы

```
cn({
  [classes.activeRepeat]: true,
  [classes.activeRepeat]: false
})
```

2022-09-08 07:01 UTC, mrerberg commented on src/components/Player/index.jsx
> +  -webkit-gradient(linear, 0% 0%, 100% 0%, color-stop(${currentPercentage}, #d9b6ff ), color-stop(${currentPercentage}, #2e2e2e ))
Вынеси формирование данных стилей в отдельную функцию

2022-09-08 07:01 UTC, mrerberg commented on src/components/Player/index.jsx
> +  const onScrubEnd = () => {
Что имеется в виду под Scrub?

2022-09-08 07:01 UTC, mrerberg commented on src/components/Player/index.jsx
> +  const { title, author, url } = audioTracks[trackIndex]
Что будет, если `audioTracks[trackIndex]` не вернет элемент?

2022-09-08 08:35 UTC, TTurkevich commented on src/components/Player/Buttons/index.jsx
> +        <div
ок, были такие подозрения

2022-09-08 09:46 UTC, TTurkevich commented on src/components/Player/Buttons/index.jsx
> +          activeRepeat
Точно, читала же про это! Спасибо!

2022-09-08 09:56 UTC, TTurkevich commented on src/components/Player/index.jsx
> +  -webkit-gradient(linear, 0% 0%, 100% 0%, color-stop(${currentPercentage}, #d9b6ff ), color-stop(${currentPercentage}, #2e2e2e ))
ok

2022-09-08 10:46 UTC, TTurkevich commented on src/components/Player/index.jsx
> +  const onScrubEnd = () => {
перетаскивание ползунка по трек бару

2022-09-08 17:20 UTC, TTurkevich commented on src/components/Player/index.jsx
> +  const { title, author, url } = audioTracks[trackIndex]
В смысле data будет с другой структурой? Или вообще не загрузится? Или, например, локальная ошибка в написании какого-то значения в data?
Печально будет, и тихо... 

Что-то не могу сообразить, проверки какие-то надо написать? Или что-то типа ErrorBoundary сделать? Или вообще изменить логику? :(

Я вообще планировала, что data будет загружаться, когда компонент плейлист формируется. И потом в компоненте с плейлистом при клике на трек, будет формироваться новая data, чтобы этот трек в ней стал первым, и прокидываться уже в плеер, отображая его. (это пока только мечты, наверняка все пойдет не так)

2022-09-09 05:45 UTC, mrerberg commented on src/components/Player/TrackPlay/index.jsx
> +const TrackPlay = ({ track, reference }) => {
Потому что ref нужно прокидывать через forwardRef

2022-09-09 05:47 UTC, mrerberg commented on src/components/Player/index.jsx
> +  const { title, author, url } = audioTracks[trackIndex]
Да можно было бы просто сделать

```
  const track = audioTracks[trackIndex]
  
  ...
  
  if(!track) return null;
  ```

2022-09-09 05:50 UTC, mrerberg requested changes

2022-09-09 05:50 UTC, mrerberg commented on src/components/Player/Buttons/index.jsx
> +  const repeatClassNames = cn({
Для константных классов можно сделать так

```
cn(classes.repeat, classes.btn, classes.btnIcon, {
    [classes.activeRepeat]: activeRepeat,
  })
```

2022-09-09 05:50 UTC, mrerberg commented on src/components/Player/Buttons/index.jsx
> +      <button
Можно сделать компонент IconButton, ты же его несколько раз используешь по сути

2022-09-09 05:50 UTC, mrerberg commented on src/components/Player/index.jsx
> +  const changeTrackStyling = () => {
А где ты возвращаешь из функции значение? Ты можешь вынести функцию из компонента, передавая аргументы

2022-09-09 06:27 UTC, TTurkevich commented on src/components/Player/Buttons/index.jsx
> +  const repeatClassNames = cn({
самое смешное, что я сначала так и сделала )) но потом подумала и переделала, мне вредно много думать

2022-09-09 06:29 UTC, TTurkevich commented on src/components/Player/index.jsx
> +  const { title, author, url } = audioTracks[trackIndex]
ведь так и сделала вчера, а потом загналась с миллионом вопросов! Спасибо

2022-09-09 12:31 UTC, TTurkevich commented on src/components/Player/Buttons/index.jsx
> +      <button
ok

2022-09-09 17:40 UTC, TTurkevich commented on src/components/Player/index.jsx
> +  const changeTrackStyling = () => {
Я ее вызвала вообще прям внутри инпута (он же трек бар) в style={...}. Скорее всего так не надо делать.
Переделала

2022-09-11 12:27 UTC, mrerberg requested changes

2022-09-11 12:27 UTC, mrerberg commented on src/components/Player/Buttons/index.jsx
> +        Icon={Prev}
На будущее, можно было бы просто в children передать, не принципиально

2022-09-11 12:27 UTC, mrerberg commented on src/components/Player/IconButton/index.jsx
> +      className={cn(classNameBtn, cn(classes.btn, classes.btnIcon))}
Обычно пишут сначала элемент, для которого назначается класс

buttonClassName
wrapperClassName

так удобнее читать, что стилизуешь

2022-09-11 12:27 UTC, mrerberg commented on src/components/Player/index.jsx
> +  if (!track) return null
у тебя не ругается линтер на это место? Все хуки должны идти ДО этого условия (useEffect и другие). Надо ниже поместить данное условие

2022-09-12 14:45 UTC, TTurkevich commented on src/components/Player/index.jsx
> +  if (!track) return null
нет, линтеру все нравится

2022-09-12 14:46 UTC, TTurkevich commented on src/components/Player/Buttons/index.jsx
> +        Icon={Prev}
ок

2022-09-12 14:47 UTC, TTurkevich commented on src/components/Player/IconButton/index.jsx
> +      className={cn(classNameBtn, cn(classes.btn, classes.btnIcon))}
ок

2022-09-13 06:42 UTC, mrerberg approved these changes

2022-09-15 14:52 UTC, merged