added a change of theme, changes have been made to the html and css
TTurkevich/player pull request #6
Opened 2022-09-23 17:54 UTC by TTurkevich

2022-09-24 14:07 UTC, mrerberg requested changes

2022-09-24 14:07 UTC, mrerberg commented on src/App/index.jsx
> +    <div className={cn(classes.wrapper, classes[`${theme}`])}>
classes[theme]

2022-09-24 14:07 UTC, mrerberg commented on src/App/index.module.css
> +.wrapper.dark {
```
.wrapper {
  &.dark {}

  &.light {}
}
```

2022-09-24 14:07 UTC, mrerberg commented on src/components/IconDisLike/index.module.css
> +.icon.dark:hover {
Самое "простое" решение темизации, это внедрение дизайн-токенов и их замена. Грубо говоря:

```
.icon {
  stroke: var(--icon-stroke);
}
```

А далее

```
:root {
 --icon-stroke: white;
}
```

[data-theme="dark"] {
:root {
 --icon-stroke: black;
}
}

2022-09-24 14:07 UTC, mrerberg commented on src/components/IconDisLike/index.module.css
> +.icon.dark:hover {
Да, будет много переменных, это нормально. Можешь посмотреть как реализовано тут

https://core-ds.github.io/core-components/master/

Но и твою реализация я приму

2022-09-24 14:42 UTC, TTurkevich commented on src/components/IconDisLike/index.module.css
> +.icon.dark:hover {
Я тоже делала такой вариант, дописала почти до конца, но в итоге засомневалась как раз из-за большого числа переменных и их названий, и все снесла. Ну и из-за наличия css-module,  мне прям принципиально было на них сделать. 
Спасибо за ссылку!

2022-09-24 14:57 UTC, TTurkevich commented on src/App/index.jsx
> +    <div className={cn(classes.wrapper, classes[`${theme}`])}>
вот это поворот, не знаю почему я так сделала

2022-09-24 15:20 UTC, TTurkevich commented on src/App/index.module.css
> +.wrapper.dark {
хм, у меня же просто css, так не работает

2022-09-29 08:10 UTC, mrerberg commented on src/App/index.module.css
> +.wrapper.dark {
Понял

2022-09-29 08:10 UTC, mrerberg commented on src/components/IconDisLike/index.module.css
> +.icon.dark:hover {
Это не проблема, много переменных = много возможностей для кастомизации

2022-09-30 06:42 UTC, merged